### ISSUE TITLE
new data training

### ISSUE THREAD

**Issue by ggfresh** [yhw-yhw/TalkSHOW#30]
Awesome work! I use a new video data to train, but find the test results are shaky and jitter.
The test data is the same as train, and the score is:
LVD=0.06410979024071979
error=10.288773031787722
diverse=0.006435648955709916
The training data is less or other training params are not setting right?
Or the show outputs are shaky?

**Comment by vibhu-raturi** [comment]
@ggfresh were you able to resolve this issue?
