### ISSUE TITLE
rendering problem

### ISSUE THREAD

**Issue by sora158** [yhw-yhw/TalkSHOW#8]
AttributeError: 'GLXPlatform' object has no attribute 'OSMesa'
> /NeRF/TalkSHOW/scripts/diversity.py(340)main()
sudo apt-get install libosmesa6
sudo apt-get install libosmesa6-dev
set os.environ['PYOPENGL_PLATFORM'] = 'osmesa' 
still doesn't work

**Comment by pxcai** [comment]
Hi, do you rendering the results successfully?  
Could you give me some advice to rendering the results?

**Comment by sora158** [comment]
> Hi, do you rendering the results successfully?  
> Could you give me some advice to rendering the results?

normally, directly get the smpl output vertices from parameters(smpl betas and shape parameters) and rendering it like pointclouds in pytorch3d is a goodway to avoid using osemesa in opengl.
